version: '3'
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: <%= ENV['POSTGRES_USER'] %>
            POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
            POSTGRES_DB: <%= ENV['POSTGRES_DB'] %>

    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/renteninfo
        ports:
            - "3000:3000"
        depends_on:
            - db