default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: renteninfo_development
test:
  <<: *default
  database: renteninfo_test

production:
  <<: *default
  database: renteninfo_production
  username: renteninfo
  password: <%= ENV['RENTENINFO_DATABASE_PASSWORD'] %>